name = "gallery-cloudflare"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "gallery-cloudflare"

[[env.production.r2_buckets]]
binding = "GALLERY_BUCKET"
bucket_name = "gallery-images"